version: '3.8'
volumes:
  postgres_data_local: {}
  postgres_backup_local: {}
services:
    db:
        image: postgres:latest
        container_name: porstgresql
        restart: always
        ports:
          - '5432:5432'
        env_file:
          - ./.env
        volumes:
          - postgres_data_local:/var/lib/postgresql/data
          - postgres_backup_local:/backups
    main:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./.env
        restart: unless-stopped
    redis:
        restart: always
        image: redis
        container_name: redis-server
        ports:
          - '6379:6379'
        env_file:
          - ./.env
networks:
    nesjs-network: